- machine_learning_hep/data/config_run_parameters.yml
- machine_learning_hep/data/database_ml_parameters.yml
- machine_learning_hep/doclassification_regression.py
- machine_learning_hep/webapp/templates/display0.html
* Updated the files which are downloaded with ml-get-data
* Updates path variables + added missing variables that were added in the new HF TTrees
* Used more compact way to write signal selection, **but** this will get updated some when we move to the bitmap selection
> Update database to most recent HF TTrees

- cplusutilities/mass_fitter.C
- machine_learning_hep/clean_analysis.sh
- machine_learning_hep/data/database_ml_analysis.yml
- machine_learning_hep/doanalysis.py
- machine_learning_hep/fit.py
- machine_learning_hep/general.py
- machine_learning_hep/listfiles.py
- machine_learning_hep/skimming.py
- setup.py
* utilities to read and list a full split dataset
* conversion root files to pandas dataframes in pkl format 
* dataframe skimming and filtering 
* analysis performed with std cuts in parallel
* analysis performed with ML in parallel:
- load a ML model
- apply ML mode and select based on probability cut
* skeleton of the complete analysis
> Add analysis framework to perform full analysis (ML and not) with python

- machine_learning_hep/doclassification_regression.py
- machine_learning_hep/mlperformance.py
TMVA-like 'response' based on that described here: https://betatim.github.io/posts/sklearn-for-TMVA-users/
> added decision boundary response histogram for training and testing data

- machine_learning_hep/selectionutils.py
Replace numpy absolute with abs since not working with numba otherwise
> Replace numpy absolute with abs

- machine_learning_hep/data/config_run_parameters.yml
- machine_learning_hep/data/database_ml_parameters.yml
- machine_learning_hep/default.yaml
- machine_learning_hep/default_complete.yaml
- machine_learning_hep/do_entire_analysis.py
- machine_learning_hep/doclassification_regression.py
- machine_learning_hep/efficiency.py
- machine_learning_hep/extractmasshisto.py
- machine_learning_hep/general.py
- machine_learning_hep/optimization.py
~~Still to test and to finish efficiency histograms for final selections.~~
~~Test needed.~~ :arrow_right:  **Tested**
> Refactor and development of efficiency functions 

- machine_learning_hep/models.py
- machine_learning_hep/optimiser.py
- machine_learning_hep/processer.py
- machine_learning_hep/utilities.py
> Add protocol=4 to pickle writes

- cplusutilities/Download.sh
- cplusutilities/downloader.sh
- cplusutilities/run_downloader
- machine_learning_hep/default_complete.yaml
- machine_learning_hep/do_entire_analysis.py
Adding the ALICE GRID Lego train downloader of ALICETreeCreator repo into the package. 
Works, but want to clean/improve the bash scripts still a bit, so WIP for the moment.
@ginnocen, please let me know how you want to add it in the  machine_learning_hep scripts. For the moment I did it simply using a flag from default_complete
> Adding ALICE LEGO train downloader

- cplusutilities/post_download.sh
The script cplusutilities/post_download.sh can be used to merge small
files from the trrHF grid production into files of desired size.
Self explanatory by typing ./post-download.sh --help
> Add post download script

- machine_learning_hep/do_entire_analysis.py
The newest version of abseil (https://github.com/abseil/abseil-py)
apparently interferes with user logging implemented via
import logging
For details see https://github.com/abseil/abseil-py/issues/99
This was observed when installing the ML package from scratch during the
last week. Comparing TensorFlow versions it was observed that most
people's ML package was still using TF version 1.13.1/2. Installing the
package now leads to installing TF vesion 1.14 and hence a more recent
version of abseil as well which causes the weird logging behaviour.
A fix is possible thanks to
https://github.com/abseil/abseil-py/issues/99#issuecomment-513414324
As soon as this is fixed in abseil this will be propagated to the ML
package.
> Temporary fix for logging

- machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml
> New sigma for LcpK0s

- cplusutilities/Download.sh
Update 2018 pp data GRID paths (kept also the old ones for the moment, as it can also be that this train was weird)
> Update Download paths pp 2018 data

- machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml
> Final Database Version LcpK0s

- machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml
This is a first attempt. The MC signal fit has to be improved further, updates of the Gaussian sigmas can hence be expected
> First attempt update sigmas

- machine_learning_hep/multiprocesser.py
- machine_learning_hep/processer.py
> Added process_response for producing MC histograms for response and feed-down.

- machine_learning_hep/correlations.py
- machine_learning_hep/optimiser.py
Fixed a bug where the signal plot were overwritten by the bkg one.
In addition now the variables used are controlled by the parameter var_all.
> Fix correlation matrix

- machine_learning_hep/analyzer.py
- machine_learning_hep/data/database_ml_parameters_D0pp.yml
- machine_learning_hep/default_apply.yml
- machine_learning_hep/default_complete.yaml
- machine_learning_hep/default_pre.yml
- machine_learning_hep/default_train.yml
- machine_learning_hep/globalfitter.py
- machine_learning_hep/multianalyzer.py
- machine_learning_hep/steer_analysis.py
This commit includes
* Putting the fitter in a class making it possible to save its fit results to a ROOT file and restore it
* a multi trial fitting procedure which does the fit in different ranges and rebinning steps (sigma is fixed, mean floats as in the nominal fit. **This can be done more fine-grained in the future if needed**). This also includes plotting these results in one canvas
* as before fit results can be found in the corresponding `results` directory of the analysis
* multi trial results are stored in the `results` directory as well
> Fitter in class and multi trial

- machine_learning_hep/analyzer.py
- machine_learning_hep/globalfitter.py
Fall back to user sigma and mean if MC pre-fit failed
> Refine fitting

- machine_learning_hep/analyzer.py
This does a quick general test whether one is within the AliPhysics env when starting the fit
The function `Analyzer.test_aliphysics()` can be called within `Analyzer` methods whenever `AliPhysics` stuff is required, e.g. before ROOT macros are called or even before `import <anyAliPhysicsStuff>` is executed
> Test if in AliPhysics env

- machine_learning_hep/data/database_ml_parameters_Dspp.yml
removing cos(theta pointing) and cos(PiDs) from the training variables list
> update Ds database

- machine_learning_hep/data/database_ml_parameters_D0pp.yml
Updated ML related parameters in D0 DB after detailed study ML performance. Improvement in significance up to 15.
Cos_t_star variable to be studied in more detail later. Important variable at pT > 4 GeV/c, but gives funky shape for bin 1-2, making it hard to fit.
> Update D0 DB after ML optimisation

- machine_learning_hep/data/database_ml_parameters_D0pp.yml
Updated to latest and greatest model
> Update D0 DB after optimisation

- machine_learning_hep/data/database_ml_parameters_D0pp.yml
Otherwise we cannot access the old application anymore
> Reset filtering prob cuts

- machine_learning_hep/data/database_ml_parameters_D0pp.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml
- machine_learning_hep/plot_hfptspectrum.py
- machine_learning_hep/ratiocase.py
Plot the interesting plots from HFPtSpectrum
> Plot the interesting plots from HFPtSpectrum

- machine_learning_hep/HFPtSpectrum.C
- machine_learning_hep/data/database_ml_parameters_Dspp.yml
- machine_learning_hep/data/database_ml_parameters_Dstarpp.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml
- machine_learning_hep/data/database_ml_parameters_LcpKpipp.yml
- machine_learning_hep/plot_hfptspectrum.py
* Merge ratiocase.py into plot_hfptspectrum.py
* Fixes database
* Some indentation fixes HFPtSpectrum
> Merge plotting macros

- machine_learning_hep/data/database_ml_parameters_LbITS2.yml
- machine_learning_hep/data/database_ml_parameters_LbITS3.yml
New variables everywhere.. + fixing some copy-paste mistakes
> Update Lb DB, new variables

- machine_learning_hep/correlations.py
- machine_learning_hep/data/database_ml_parameters_LbITS2.yml
- machine_learning_hep/data/database_ml_parameters_LbITS3.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp_20190923_tmp.yml
- machine_learning_hep/mlperformance.py
- machine_learning_hep/models.py
- machine_learning_hep/optimiser.py
* Update layout plots
* Fix bugs ml_study Lb database
* Create temporary LcpK0s database for processing new data (should be removed after transition from 4 trains to 3 train)
> Layout plots, update Lc DB, fix Lb DB

- machine_learning_hep/correlations.py
v_training was overwriting v_all
> Fix not overwriting plot

- machine_learning_hep/analyzer.py
- machine_learning_hep/correlations.py
- machine_learning_hep/default_apply.yml
- machine_learning_hep/default_pre.yml
- machine_learning_hep/default_train.yml
* Raw yield should not be divided by binwidth for HFPtSpectrum
* Some flags to true in default_completes for storing ML plots
> Fix fitter for HFPtSpectrum

- machine_learning_hep/analyzer.py
- machine_learning_hep/data/database_ml_parameters_D0pp.yml
- machine_learning_hep/default_train.yml
- machine_learning_hep/optimiser.py
- machine_learning_hep/optimization.py
- machine_learning_hep/processer.py
Some fixes + new probability cuts for D0 after looking at significance plots
> random fixes + new cuts for D0

- machine_learning_hep/data/database_ml_parameters_Bs.yml
- machine_learning_hep/data/database_ml_parameters_D0pp.yml
- machine_learning_hep/data/database_ml_parameters_Dspp.yml
- machine_learning_hep/data/database_ml_parameters_Dstarpp.yml
- machine_learning_hep/data/database_ml_parameters_LbITS2.yml
- machine_learning_hep/data/database_ml_parameters_LbITS3.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml
- machine_learning_hep/data/database_ml_parameters_LcpKpipp.yml
* Multiplicity ranges 0 ->  1
* Merged bins 2-3-4 and 4-5-6
* Added spdhits_prong for next processing (already available for Lc's)
* Added missing v0m perc analyses for pKpi
* Small fixes
> Get highmult DB's at same level

- machine_learning_hep/ana.sh
- machine_learning_hep/data/database_ml_parameters_D0pp.yml
- machine_learning_hep/data/database_ml_parameters_Dspp.yml
- machine_learning_hep/data/database_ml_parameters_LbITS2.yml
- machine_learning_hep/data/database_ml_parameters_LbITS3.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml
- machine_learning_hep/data/database_ml_parameters_LcpKpipp.yml
- machine_learning_hep/plot_hfmassfitter.py
- machine_learning_hep/plot_hfptspectrum.py
Store plots in folder in DerivedResults. 
Edit ana.sh that they are automatically run.
Add Signal, Background plots
Add efficiency ratio plot
Fixes
> Store plots in folder in DerivedResults

- machine_learning_hep/ana.sh
- machine_learning_hep/plot_hfptspectrum_years.py
Include plotting macro for year-comparison in new flow
> Include year plotting

- machine_learning_hep/analyzer.py
- machine_learning_hep/data/database_ml_parameters_Bs.yml
- machine_learning_hep/data/database_ml_parameters_D0pp.yml
- machine_learning_hep/data/database_ml_parameters_Dspp.yml
- machine_learning_hep/data/database_ml_parameters_Dstarpp.yml
- machine_learning_hep/data/database_ml_parameters_LbITS2.yml
- machine_learning_hep/data/database_ml_parameters_LbITS3.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml
- machine_learning_hep/data/database_ml_parameters_LcpKpipp.yml
- machine_learning_hep/default_ana.yml
- machine_learning_hep/default_apply.yml
- machine_learning_hep/default_complete.yaml
- machine_learning_hep/default_complete_MBvspt_ntrkl.yaml
- machine_learning_hep/default_complete_MBvspt_v0ml.yaml
- machine_learning_hep/default_complete_SPDvspt.yaml
- machine_learning_hep/default_complete_V0mvspt.yaml
- machine_learning_hep/default_pre.yml
- machine_learning_hep/default_train.yml
- machine_learning_hep/multisystematics.py
- machine_learning_hep/steer_analysis.py
- machine_learning_hep/systematics.py
* Estimate probability cut range that varies efficiency with X% (done, vars to be added in DB)
* Make input mass + efficiency rootfiles (done)
* Fit mass histograms (done)
* Extract efficiencies (done)
* Get corrected spectra using HFPtSpectrum (done)
* Plot + extract the systematic value (done, systematic value to be extracted)
> Introduce cut variation in package

- machine_learning_hep/analyzer.py
- To be replaced by skipping mult bins below threshold
> Temporary protection for null division

- machine_learning_hep/HFPtSpectrum.C
- machine_learning_hep/systematics.py
Crash due to loop over HFPtSpectrum.C that didn't close its files
> Too many files open bug fix

- machine_learning_hep/analyzer.py
- machine_learning_hep/data/database_ml_parameters_Dspp.yml
Put the applied pickles in a separate _opt directory for the moment as the trained model was slightly different (same master, but different randomised data taken for training, so slightly different working point)
> Optimise Ds fits + extra features

- machine_learning_hep/analyzer.py
- machine_learning_hep/data/database_ml_parameters_Dspp.yml
> Fix of previous PR

- machine_learning_hep/data/database_ml_parameters_Dspp.yml
- machine_learning_hep/data/database_ml_parameters_DsppSTD.yml
- machine_learning_hep/systematics.py
* Fix cut variation fitter with recent fitter updates
* Add STD database getting pp5TeV cuts using bit
> Fix systematics with recent fitter updates

- machine_learning_hep/data/database_ml_parameters_Dspp.yml
- machine_learning_hep/systematics.py
Missing new variable in DB's
Improve a bit cut variation plots
> Late night fixes

- machine_learning_hep/processer.py
Instead of printing for each file, print info statements once
> Remove spam when running

- machine_learning_hep/data/database_ml_parameters_Bs.yml
- machine_learning_hep/data/database_ml_parameters_D0pp.yml
- machine_learning_hep/data/database_ml_parameters_DsPbPb3050.yml
- machine_learning_hep/data/database_ml_parameters_Dstarpp.yml
- machine_learning_hep/data/database_ml_parameters_LbITS2.yml
- machine_learning_hep/data/database_ml_parameters_LbITS3.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml
- machine_learning_hep/optimiser.py
- machine_learning_hep/optimization.py
- machine_learning_hep/steer_analysis.py
(I messed up with git in the last PR)
This PR add the possibility to change the bkg fit function used in the significance optimization. Moreover the estimation of the model efficiency as a function of the threshold is added.
> Add estimation of model efficiency + improvement of sig. opt. (fixed)

- machine_learning_hep/multiprocesser.py
Note: This needs a more general fix in the future
> Call jet-specific processer methods savely

- machine_learning_hep/fitting/fitters.py
- machine_learning_hep/fitting/helpers.py
* Important fix as signal and background function were passed in the
wrong order to the constructor of the AliHFInvMassFitter
* Add verbosity to MLFitter
* Draw fits also when they failed
> Fix order of sig and bkg function

- setup.py
Fix version of dependencies to ensure reproducibility.
> fix versions in setup.py

- machine_learning_hep/analysis/analyzer.py
- machine_learning_hep/analysis/analyzer_manager.py
- machine_learning_hep/analysis/systematics.py
* Add merged analyzer to AnalyzerAfterBurner
* Add optional significance and Chi2 thresholds for mass fits in
systematics
> Small updates for systematics

- machine_learning_hep/data/FF/database_ml_parameters_D0pp_FF.yml
- machine_learning_hep/data/database_ml_parameters_Bs.yml
- machine_learning_hep/data/database_ml_parameters_D0pp.yml
- machine_learning_hep/data/database_ml_parameters_DsPbPb010.yml
- machine_learning_hep/data/database_ml_parameters_DsPbPb3050.yml
- machine_learning_hep/data/database_ml_parameters_Dspp.yml
- machine_learning_hep/data/database_ml_parameters_Dspp_test.yml
- machine_learning_hep/data/database_ml_parameters_Dspp_test_bkg.yml
- machine_learning_hep/data/database_ml_parameters_Dstarpp.yml
- machine_learning_hep/data/database_ml_parameters_LbITS2.yml
- machine_learning_hep/data/database_ml_parameters_LbITS3.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp_test.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp_test_0201.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp_test_0909.yml
- machine_learning_hep/data/database_ml_parameters_LcpK0spp_test_0923.yml
- machine_learning_hep/data/database_ml_parameters_LcpKpipp.yml
- machine_learning_hep/submission/README.md
- machine_learning_hep/submission/default_ana.yml
- machine_learning_hep/submission/default_apply.yml
- machine_learning_hep/submission/default_complete.yaml
- machine_learning_hep/submission/default_pre.yml
- machine_learning_hep/submission/default_train.yml
- machine_learning_hep/submission/run_all.sh
- machine_learning_hep/submission/run_case.sh
- machine_learning_hep/submit_0201.sh
> Improve databases and scripts.

- machine_learning_hep/grid_search.py
- machine_learning_hep/optimiser.py
Avoid crashes connected to plotting and do not risk losing results. Save
everything as soon as it is available.
For each model one directory is created and
* the best one is saved
* grid search parameters are written
* results/scores are saved
> Save results asap before plotting

- machine_learning_hep/data/FFLc/database_ml_parameters_LcpK0spp_20200301.yml
Hi @vkucera @DelloStritto @nzardosh. I put back the two databases together. I think it can help synchronizing since we will both us MB data and the same optimised model.
> merge Lc database

- machine_learning_hep/data/FFLc/database_ml_parameters_LcpK0spp_20200301.yml
- machine_learning_hep/submit_20200303.sh
@arthur-gal @DelloStritto @vkucera @nzardosh this is a tiny production but it is as the final one. So this database can be used for crosschecking all the details.
> Use train test, realistic production

- machine_learning_hep/data/JetAnalysis/systematics/database_ml_parameters_D0pp_zg_0304_default_1.yaml
- machine_learning_hep/submit_full_jets.sh
No one look, adding bash script of shame
> adding the actual systematics bash script

- Analyses/ALICE_D2H_vs_perc_v0m_pp13/plot_final_results_d0_lc.py
- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_zg_0304.yml
* add first plotting macro
* enable include_reflection flag in V0M perc analysis in D0 DB
> Add final result macros for V0M perc. analysis

- machine_learning_hep/analysis/analyzer_jet.py
- machine_learning_hep/processer.py
- machine_learning_hep/processerdhadrons.py
- machine_learning_hep/processerdhadrons_jet.py
The PR #585 has introduced changes which were not propagated properly to the other processors and the jet analyzer.
> Fix the bugs caused by the changes in the multiplicity analyses.

- machine_learning_hep/analysis/analyzer_Dhadrons.py
- machine_learning_hep/analysis/analyzer_back.py
- machine_learning_hep/analysis/analyzer_jet.py
- machine_learning_hep/analysis/analyzer_jet_legacy.py
- machine_learning_hep/analysis/analyzerdhadrons_mult.py
- machine_learning_hep/data/JetAnalysis/database_ml_parameters_D0pp_FF.yml
- machine_learning_hep/data/JetAnalysis/database_ml_parameters_D0pp_zg.yml
- machine_learning_hep/data/JetAnalysis/database_ml_parameters_LcpK0spp_test.yml
- machine_learning_hep/data/JetAnalysis/database_ml_parameters_LcpK0spp_test_0201.yml
- machine_learning_hep/data/JetAnalysis/database_ml_parameters_LcpK0spp_test_0201_D2H.yml
- machine_learning_hep/data/JetAnalysis/database_ml_parameters_LcpK0spp_test_0909.yml
- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_0304.yml
- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_Dspp.yml
- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_Bs.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_D0pp.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_DsPbPb010.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_DsPbPb3050.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_Dspp_test.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_Dspp_test_bkg.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_Dstarpp.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_LbITS2.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_LbITS3.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_LcpK0spp.yml
- machine_learning_hep/data/obsolete/database_ml_parameters_LcpKpipp.yml
- machine_learning_hep/data/pKpi/database_ml_parameters_LcpKpi010.yml
- machine_learning_hep/examples/plot_hfmassfitter.py
- machine_learning_hep/examples/plot_hfptspectrum.py
- machine_learning_hep/examples/plot_hfptspectrum_years.py
- machine_learning_hep/fitting/helpers.py
> Baryon emancipation

- machine_learning_hep/do_systematics.py
If a category that requires running the processor is about to be started, check whether the output directories exist and if they do, provide the user with the option to delete them before starting the analysis.
> Prompt to delete output directories before running the processor.

- machine_learning_hep/utilities_plot.py
- machine_learning_hep/utilities_validation.py
> Add plots for V0M vs ntrklt

- machine_learning_hep/fitting/fitters.py
- machine_learning_hep/fitting/simple_fit.py
* usable from the command line or inside another class/function/module
* only relies on path to database YAML, analysis name and preiod number
> Add stand-alone fitting macro

- machine_learning_hep/analysis/analyzerdhadrons_mult.py
- machine_learning_hep/steer_analysis.py
This PR introduces a skeleton function for performing final plots for the validation.
> Add skeleton for validation function

- machine_learning_hep/fitting/helpers.py
* fix en-/disabling free sigma for trials
* skip multi trials without parameters
> Small fixes for multi trial

- machine_learning_hep/analysis/analyzerdhadrons_mult.py
- machine_learning_hep/utilities_plot.py
- machine_learning_hep/validation/validation.py
- machine_learning_hep/validation/validation_candidates.py
- machine_learning_hep/validation/validation_multiplicity.py
- Histograms of non existing columns are not filled
- Add proton PID information for TPC-TOF matching efficiency
- Reworked order of plot making
> Checking on column existance before making histograms

- machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml
* add CALO triggers in event selection
* fixed low pT D0
> Make D0 DB ready for new grid prodction

- machine_learning_hep/config.py
- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_0304.yml
- machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml
- machine_learning_hep/steer_analysis.py
* revise config.py
* parameter database is adjusted based on parameter settings
* first use case is to adjust ML paths when doing STD analysis appending
"_std" to corresponding paths
> Updating database before usage

- machine_learning_hep/analysis/README.md
- machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml
- machine_learning_hep/processer.py
- machine_learning_hep/processerdhadrons_mult.py
* introduce Cut class to centralise cut treatment
* add helper function for making query from Cut objects
* apply analysis cuts in in processerdhadrons_mult.py
* remove process_histomass from processerdhadrons_mult since it is a
duplicate of the one on processer.py
> Apply additional custom cuts

- machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml
change the mass windows of raw yield systematic uncertainty
> Minor changes D0 database

- .github/workflows/pythonpackage.yml
- ci/flake8-ignore
- ci/pylint-ignore
- ci/pytest/test_general.py
- ci/run-tests.sh
Set files to be ignored in ci/pylint-ignore
> Upgrade CI

- machine_learning_hep/utilities.py
The function `make_plot` allows to produce a nice plot with a single command while supporting the usual object types and offering the flexibility to set most of the style aspects.
Description
Make a plot with objects from a list (`list_obj`).
Returns a `TCanvas` and a list of other created ROOT objects.
Minimum example:
`make_plot("canvas", list_obj=[histogram], path=".")`
To have access to the created object, do:
`canvas, list_can = make_plot("canvas", list_obj=[histogram])`
Features
- plotting of histograms (`TH??`), graphs (`TGraph*`), text fields (`TLatex`) and any other objects derived from `TObject` in any count and order
- automatic calculation of plotting ranges (x, y) based on the data (histograms and graphs)
- arbitrary x range
- automatic style settings
- optional plotting of …
> The Ultimate Plotting Function (TUPF)

- machine_learning_hep/analysis/analyzerdhadrons_mult.py
- machine_learning_hep/processerdhadrons_mult.py
- machine_learning_hep/validation/validation.py
- machine_learning_hep/validation/validation_candidates.py
- Improve validation code
- Improve verbose mode
- Add pt_cand TPC-TOF M.E.
- Add reco w/wo TOF in efficiency
> Validation dev

- machine_learning_hep/fitting/fitters.py
* fix wrong usage of AliHFInvMassMultiTrialFit::SetFixRefoS
* consistent usage of AliVertexingHFUtils::AdaptTemplateRangeAndBinning
> Updates for multi trial with reflections

- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml
- machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml
- machine_learning_hep/fitting/fitters.py
- machine_learning_hep/fitting/helpers.py
...and small enhancements of fitting
> Update V0M analyses in D0 and LcpK0s DBs

- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_0304.yml
- machine_learning_hep/processerdhadrons_jet.py
Hi @nzardosh @vkucera please have a quick crosscheck.
> Add option to switch off jet selection for D efficiencies

- machine_learning_hep/models.py
- machine_learning_hep/optimiser.py
- machine_learning_hep/steer_analysis.py
- machine_learning_hep/submission/default_ana.yml
- machine_learning_hep/submission/default_analyzer.yml
- machine_learning_hep/submission/default_apply.yml
- machine_learning_hep/submission/default_complete.yml
- machine_learning_hep/submission/default_pre.yml
- machine_learning_hep/submission/default_systematics.yml
- requirements.txt
- setup.py
Use SHAP (https://github.com/slundberg/shap) for feature importance when
using decision trees.
This is enabled by setting ml_study/doimportanceshap to true in the run
configuration
> Add feauture importance study plot with SHAP

- machine_learning_hep/analysis/systematics.py
- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml
Delete the runlisttrigger and validation from systematics
> remove validation from DB

- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml
- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304_HM_V0.yml
- machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml
- machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417_HM_V0.yml
- machine_learning_hep/fitting/helpers.py
* prelim. finalisation of D0 and Lc DBs for MB and V0HM analysis
* fitter doesn't anymore fail when pre-fits are non successful but
sigma should be taken from user anyway
> Update DBs and small fit update

- machine_learning_hep/utilities_plot.py
Propagate the modifications for the HP20 DvsMult preliminaries:
* Include BR systematic in boxes
* Add stat. unc. efficiency as systematic. Note: this was not yet included in the HP20 preliminaries, but will be for the paper
* Functions to average Lc -> pKpi and Lc -> pK0s using the standard ALICE method. Note: Pushed the version that includes the stat. unc. efficiency. HP20 preliminaries were done without this source
* Some small fixes
> HP20 modifications for DvsMult systematics

- machine_learning_hep/analysis/README.md
- machine_learning_hep/analysis/analyzerdhadrons_mult.py
- machine_learning_hep/config.py
- machine_learning_hep/do_variations.py
- machine_learning_hep/processerdhadrons_mult.py
- machine_learning_hep/root.py
* add possibility to take efficiencies from a chosen multiplicity bin of
another analysis
* start development of concise meta data object to not hide all
information of pT, mutliplicity and ML working point in a file  or
histogram name (see MLHEPMetaInfo in root.py)
* add an option to add missing keys in modify_dictionary in
do_variations.py
> Analysis and efficiency update

- machine_learning_hep/HFPtSpectrum.C
I ignored some less interesting histograms from the original HFPtSpectrum macro. Added them now also for HFPtSpectrum2 (the corrected yield per event in multiplicity bins)
> Improve HFPtSpectrum for multiplicity bins

- machine_learning_hep/analysis/analyzer_jet.py
- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304_jet.yml
- machine_learning_hep/processerdhadrons_jet.py
Replace z > 0.99 with 0.99 to include z = 1 in the range 0-1.
> Truncate z.

- machine_learning_hep/utilities_plot.py
Small issues fixed. Found by Mattia when averaging the Sigmac analysis
> Fixes to Lc averaging code

- machine_learning_hep/derive_weights/derive_weights.py
- machine_learning_hep/derive_weights/perc_v0m/weights_config_D0_HM_data.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_D0_HM_mc.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_D0_MB_data.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_D0_MB_mc.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_Lc_HM_data.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_Lc_HM_mc.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_Lc_MB_data.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_Lc_MB_mc.yaml
* no binomial division
* add options on whether to use
* mass window
* ML cuts
both used by default
* is_ev_rej == 0 has to be provided by the user in the config YAML e.g.
using the "query_all" field
> Update weights derivation

- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml
- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304_HM_V0.yml
- machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml
- machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417_HM_V0.yml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_D0_HM_data.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_D0_MB_data.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_Lc_HM_data.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_Lc_HM_mc.yaml
- machine_learning_hep/derive_weights/perc_v0m/weights_config_Lc_MB_data.yaml
- machine_learning_hep/fitting/fitters.py
- machine_learning_hep/fitting/helpers.py
* fitter ready for double Gaussian pre-fit
use 'pre_fits_mc' in database to specify kGaus or k2Gaus per pT bin
optional, default is kGaus
* MC pre-fit (single Gaussian) in at least 3 RMS range
* perc_v0m MC weights configuration applies same data and MC selection
> Update DBs, MC weight configs, fitter

- machine_learning_hep/fitting/helpers.py
- machine_learning_hep/models.py
- machine_learning_hep/processer.py
- machine_learning_hep/processerdhadrons_mult.py
Possibility to apply + analyse multiclassification models (needed for Ds vs mult analysis)
Feature to train the model using multiclassification in MLHEP to be added. This needs some larger changes in optimiser.py. I would postpone this to a later stage after the paper proposal
> Add option to apply+analyse multiclassification models

- machine_learning_hep/analysis/analyzerdhadrons_mult.py
- machine_learning_hep/processer.py
- machine_learning_hep/processerdhadrons.py
- machine_learning_hep/processerdhadrons_jet.py
- machine_learning_hep/processerdhadrons_mult.py
* procs
* already reading ML WPs from analysis section rather than from
mlapplication section. Falling back to latter if former fails
* move ML cut string generation for querying dataframes to
parent-class Processer instead of duplicating it in each deriving
class
* analyzerdhadrons_mult
* short update/fix in fit() and yield_syst() methods
* add method to extract efficiency in certain bin
> Update procs and analyzerdhadrons_mult

- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml
- machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304_HM_V0.yml
- machine_learning_hep/fitting/fitters.py
- machine_learning_hep/fitting/helpers.py
- machine_learning_hep/fitting/utils.py
* introduce dynamic rebinning strategy
* set
dynamic_rebinning: True
in the database (optional, if not present fallback to original
strategy)
* pass a tuple of (min_rebinning, entries_per_bin, max_rebinning) and
1) check average entries per bin. if smaller than "entries_per_bin",
rebin accordingly
2) if min_rebinning > dynamic_rebinning take min_rebinning
3) if dynamic_rebinning > max_rebinning take max_rebinning
* still backwards-compatible hence working with an explicit rebinning
value
> Fit rebinning strategy

- machine_learning_hep/validation/README.md
- machine_learning_hep/validation/find_duplicates_events.py
The script
validation/find_duplicates_event.py
can find out whether there are events with duplcaited combination of
[ev_id, ev_id_ext, run_number]
For more info, see README in validation
> Add event duplication check

- cplusutilities/Download-generic.sh
- cplusutilities/run_downloader
* account for possible pass/AOD in MC
* fix printed GRID path in run_downloader when Download-generic.sh is
used
> Update GRID download
