machine_learning_hep/data/config_run_parameters.yml, machine_learning_hep/data/database_ml_parameters.yml, machine_learning_hep/doclassification_regression.py, machine_learning_hep/optimization.py, machine_learning_hep/webapp/templates/display0.html
* Added bitmap selection also in significance optimisation (tested for D0, looks good. More tests might be needed)
* Adding other HF mesons (Ds, Dplus, Dstar, and Lc's) again.
NB: One should run ml-get-data again, as the files are updated
NB2: The SmallSkimmed MC files for Lc don't have enough signal for the moment. Will get updated in the dropbox folder.
NB3: Pre-PID&Track-selection turned on by default for all HF mesons except for Ds. Here there seems to be a bug with these bits set in AliPhysics, as all events get rejected
=> Finalising bitmap

machine_learning_hep/doanalysis.py, machine_learning_hep/doclassification_regression.py
Currently the dataframe containing the events of all data production is created two times. With this PR it will be created only in the skimming phase. In this way few GB of space, for each analysis, will be saved.
=> Remove double production of event dataframes

machine_learning_hep/data/database_ml_parameters_D0pp_jets.yml, machine_learning_hep/data/database_ml_parameters_D0pp_multiplicity.yml, machine_learning_hep/data/database_ml_parameters_Dspp_multiplicity.yml, machine_learning_hep/data/database_ml_parameters_DstoKKpiPbPbCen3050.yml, machine_learning_hep/data/database_ml_parameters_LcpK0s_multiplicity.yml, machine_learning_hep/data/database_ml_parameters_LcpK0s_multiplicity_test.yml, machine_learning_hep/data/database_ml_parameters_LcpK0s_pt.yml, machine_learning_hep/data/database_ml_parameters_LcpKpi_multiplicity.yml, machine_learning_hep/multiprocesser.py, machine_learning_hep/optimiser.py, machine_learning_hep/processer.py
For pp events, it is currently not possible to create a total merged evt sample because of the too large statistics (RAM memory error). For the moment a switch is introduced to turn off the merging when the flag is off. In the future I will introduce a parallelized loop to calculate the total number of events in the significance optimization tool so that producing a total merged event dataframes will not be needed.
=> Temporary fix to avoid total merging of event df to avoid RAM error

cplusutilities/Download.sh
* Moving childs of the same train to different output folders in the Download macro. Allows to run multiple productions in one train
=> Add moving to different folders

machine_learning_hep/default_ana.yml, machine_learning_hep/default_apply.yml, machine_learning_hep/default_complete.yaml, machine_learning_hep/default_complete_MBvspt_ntrkl.yaml, machine_learning_hep/default_complete_MBvspt_v0ml.yaml, machine_learning_hep/default_complete_SPDvspt.yaml, machine_learning_hep/default_complete_V0mvspt.yaml, machine_learning_hep/default_pre.yml, machine_learning_hep/default_train.yml, machine_learning_hep/processer.py, machine_learning_hep/steer_analysis.py
Possibility to "pause" the heavy application operation by stopping the python job. Uses a flag in the default_complete to skip the already processed files when process is restarted.
Used a lot when applying for the Lc in PbPb analysis, files don't get corrupted
=> Possibility to skip already applied files

cplusutilities/Download.sh, machine_learning_hep/HFPtSpectrum.C, machine_learning_hep/HFPtSpectrum2.C, machine_learning_hep/ana.sh, machine_learning_hep/analyzer.py, machine_learning_hep/data/database_ml_parameters_D0pp.yml, machine_learning_hep/data/database_ml_parameters_Dspp.yml, machine_learning_hep/data/database_ml_parameters_LcpK0spp.yml, machine_learning_hep/data/database_ml_parameters_LcpKpipp.yml, machine_learning_hep/systematics.py
* Full MC ready, so new paths
* Added 2nd HFPtSpectrum script that uses the fPrompt fraction from a HFPtSprectrum.root as input file, to calculate the corrected yield/cross section. Tested at AliPhysics level, not yet in the MLHEP package. Therefore WIP
TODO: Use MB input file for HM triggered analysis mode. Now it is taking mult-int in HM triggered data. Should also work when MB file is not run yet, as things are going in parallel
=> Use fPrompt from MB for HM + Update downloader

machine_learning_hep/systematics.py, setup.py
There was a mismatch between pylint from package (2.3.1) and the one Travis used (2.4.3) with different end result on "disable=import-outside-toplevel". Forced package to take same version as Travis
=> Bump pylint to same version as Travis

machine_learning_hep/data/database_ml_parameters_DsPbPb3050.yml, machine_learning_hep/default_apply.yml, machine_learning_hep/default_complete.yaml, machine_learning_hep/default_pre.yml, machine_learning_hep/default_train.yml, machine_learning_hep/mlperformance.py, machine_learning_hep/optimiser.py, machine_learning_hep/steer_analysis.py
Add the possibility to compare the model prediction for signal and bkg on the training and test set, useful to check for over-training. This PR slightly modify and makes callable again the function implemented by @jaimenorman in #78
=> Add plot of model predictions on train and test set

machine_learning_hep/analyzer.py, machine_learning_hep/fitting/__init__.py, machine_learning_hep/fitting/fitters.py, machine_learning_hep/fitting/helpers.py, machine_learning_hep/fitting/utils.py, machine_learning_hep/multianalyzer.py, machine_learning_hep/utilities.py
Fitting in the package has been moved to the sub-module fitting where
there are
1) fitters.py
Containing actual fitting classes. Basically independent of the MLHEP
package. No need to know anything about user-interfaces or workflows.
2) utils.py
Here are common functions dealing with a fitter. At the moment there
are 2 functions taking care of writing/reading fitters to/from disk.
3) helpers.py
These are helper classes being aware of e.g. the MLHEP database
configuration and providing fast construction and access to fit needed
within the MLHEP workflow.
1) and 2) are independent of the MLHEP package and they don't  know
anything about user-interfaces or workflows. 3) is then providing the
interface to the MLHEP workflows and some implementations.
NOTE: The systematic (aka multi-trial) has …
=> Refactory of fitting

machine_learning_hep/analysis/analyzer.py, machine_learning_hep/analysis/multianalyzer.py, machine_learning_hep/fitting/fitters.py, machine_learning_hep/fitting/helpers.py
The multianalyzer calls the analyzer base class with the desired
analysis steps as string. The presence of a corresponding method is
checked which is then executed. Non-present analysis steps are collected
and reported to be missing at the end.
In that way the multianalyzer does not need to be aware of any analysis
method but just tries the analyzer classes.
=> Make (multi)analyzer analysis calls flexible

machine_learning_hep/analysis/utils.py, machine_learning_hep/steer_analysis.py
Only works if result directories per period and merged result directory
already exist. Cannot at the moment not be run independent of mass
histogram creation as this would always complain if the a result
directory already exists.
=> Move preparenorm for mult analysis

machine_learning_hep/processer.py, machine_learning_hep/submission/default_complete.yml
* Files like
<path/to/pklskml>/{AnalysisResultsEvt.pkl.lz4,AnalysisResultsEvtOrig.pkl.lz4}
are not produced anymore as their production might demand
O(10GB)-O(100GB) or RAM which could lead to a crash.
* Significance optimisation potentially affected and might not work at
the moment. This has to be revised.
* See comments in Processer.process_mergeforml()
=> Avoid RAM overflow when creating ML files

machine_learning_hep/analysis/analyzerdhadrons_mult.py, machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_20200301.yml, machine_learning_hep/steer_analysis.py
* Don't print GeV for multiplicity bins in final result plots
* Set ROOT batch mode right from the beginning to avoid printing/showing
default TCanvas
* Change mult label in v0m_perc analysis
=> Small updates

machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_20200301.yml
This is just a small PR, however, introducing minimal significance and maximum red. chi2 for ML systematic fits so it's centrally available in the database now
=> Add max chi2 and min signif for ML syst

machine_learning_hep/analysis/analyzer_jet.py, machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_zg_0304.yml, machine_learning_hep/data/data_prod_20200304/database_systematics_D0pp.yml, machine_learning_hep/do_systematics.py
The script modifies a given database based on the differences specified in a variation database and optionally starts the analysis.
- The database contains variations of parameters grouped into categories.
- Each category or variation has an activation flag (to enable/disable it) and a label which can be used in a formatted output or plotting.
- The modifications are in the "diffs" key of each variation and they must follow the same structure as the given database, starting at the second level (first indented entries).
- A correct structure of the variation database is checked and errors are reported.
- The script loops over enabled categories and variations and replaces the content of the database with the content in diffs.
- It is possible to use a single value to modify all elements of …
=> Add the systematics script and a basic variation database.

machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_0304.yml, machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml, machine_learning_hep/fitting/README.md, machine_learning_hep/fitting/fitters.py, machine_learning_hep/fitting/helpers.py
Decide separately on relative up- and downward variation of central
sigma per pT bin.
This is optional in the analysis part in the database (within the
systematic section)
`rel_var_sigma_up: [val_up_pT_bin0, val_up_pT_bin1, ...]`
`rel_var_sigma_down: [val_down_pT_bin0, val_down_pT_bin1, ...]`
Values that evaluate to `False` are ignore.
=> Add fixed sigma variation multi-trial

cplusutilities/post_download.sh
Create the log directory in $HOME to avoid the write permission problem with the /tmp directory.
Make the log directory name unique to avoid overwriting.
=> Improve logging.

machine_learning_hep/HFPtSpectrum.C, machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_0304.yml, machine_learning_hep/data/data_prod_20200304/database_ml_parameters_Dspp.yml, machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml, machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml
Fixed the HFPtSpectrum macro for the trigger efficiency bug (Nevents * eff_trig -> Nevents / eff_trig) coming from a misunderstanding of a variable called TriggerEfficiency in the AliPhysics HFPtSpectrum.C macro.
PR = WIP because our analyzer is now not doing it correctly ([this part](https://github.com/ginnocen/MachineLearningHEP/blob/5e07d5456940b919f0bf9487e2b77c31f6b1ed98/machine_learning_hep/analysis/analyzerdhadrons_mult.py#L471-L506)). Correct strategy is:
1. Run AliPhysics HFPtSpectrum macro (HFPtSpectrum() in our macro) for yield-efficiency-nEvents in [0-9999], no trigger efficiency. So the usual cross section case. Need to do this to get the MB fprompt.
2. Run the for-multiplicity-bins changed HFPtSpectrum macro (HFPtSpectrum2() in our macro) for yield-efficiency-nEvents in …
=> Trigger efficiency fix corrected yield macro

ci/flake8-ignore, ci/pylint-ignore, machine_learning_hep/analysis/analyzer.py, machine_learning_hep/analysis/analyzer_jet.py, machine_learning_hep/analysis/analyzerdhadrons.py, machine_learning_hep/analysis/analyzerdhadrons_mult.py, machine_learning_hep/fitting/helpers.py, machine_learning_hep/processing/__init__.py, machine_learning_hep/processing/multiprocesser.py, machine_learning_hep/processing/processer.py, machine_learning_hep/processing/processerdhadrons.py, machine_learning_hep/processing/processerdhadrons_jet.py, machine_learning_hep/processing/processerdhadrons_mult.py, machine_learning_hep/processing/utils.py, machine_learning_hep/steer_analysis.py
* revive analysis/analyerdhadrons.py
* move processer related code to processing sub-directory
* introduce ProcesserHelper for common operation
(at the moment only construction mass histogram suffices)
can and should be used in Processer and Analyzer classes. In both
cases the parent classes have an object self.processer_helper which
can be used in derivin classes
* updated MLFitter to comply with inclusive analysis
=> Restructure and add inclusive analyzer

machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml, machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml, machine_learning_hep/processerdhadrons_mult.py
* add weight file to data/event_weighting_mc used for weighting in V0M
analysis
* allow for specification of how MC should be re-weighted in database
refer to database
data/data_prd_20200304/database_ml_parameters_LcpK0spp_0304.yml
and there check the analysis MBvspt_perc_v0m and in there one finds
the field event_weighting_mc
* this is at the moment only implemented in processerdhadrons_mult.py
=> Generic MC event reweighting

cplusutilities/Download-generic.sh
Since some time (~ a year), a GRID merging step is automatically performed for derived data productions (up to 1GB). Stored in the AOD/ folder. A lot faster to download those (especially for MC)
And a typo fix: 10TB -> 1TB
=> Download GRID merged version of derived data productions

machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml, machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304_HM_V0.yml, machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml, machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417_HM_V0.yml
* binning adjustment for perc_v0m analysis to include value of 100.
otherwise the number of selected events is not estimated correctly
when this percentile value is included
* use HM V0 inclusive (aka D2H) MC for Lc in 0.-0.1
* remove run selection for 2016 MB in perc_v0m analysis
* update FONLL file where not yet done
* SetInitialGaussianMean to False in perc_v0m already. This will be used
by the fitter in the future
=> Update D0, Lc DBs

ci/pylint-ignore, machine_learning_hep/analysis/analyzer_manager.py, machine_learning_hep/analysis/systematics.py, machine_learning_hep/steer_analysis.py, machine_learning_hep/submission/default_ana.yml, machine_learning_hep/submission/default_analyzer.yml, machine_learning_hep/submission/default_apply.yml, machine_learning_hep/submission/default_complete.yml, machine_learning_hep/submission/default_pre.yml, machine_learning_hep/submission/default_systematics.yml, machine_learning_hep/submission/default_train.yml
* ML systematics re-written to EXACTLY match the nominal analysis
workflow. To ensure that, it uses instances of the the
corresponding MultiProcesser and Analyzer classes.
--> Code much cleaner and easier to understand
* steps:
1) derive lower and upper boundaries of ML WP within required
efficiency variation (usually +/- 25%, to be set in the DBs)
2) for a given number of trials, derive new WPs around nominal
working points
3) Do entire analysis chain for all WPs. This produces the full
Processer and Analyzer output in
`$NOMINAL_RESULT_DIR/ML_WP_syst/trial_<i>` and summary plots in
`$NOMINAL_RESULT_DIR/ML_WP_syst`
A systematic run can be interrupted by Ctrl-C. Press only once and
wait. That ensures that the configuration is serialised to disk. After
that the systematics can always be …
=> Re-write ML systematics

machine_learning_hep/analysis/systematics.py, machine_learning_hep/fitting/fitters.py, machine_learning_hep/fitting/helpers.py, machine_learning_hep/fitting/utils.py
* close ROOT files after usage in fitting, helpers and utils
* don't re-initialise a fitter kernel when fit is loaded from disk
* obtain fitter from nominal analyzer if available in ML syst
=> Small tidying up

machine_learning_hep/analysis/analyzerdhadrons_mult.py, machine_learning_hep/analysis/systematics.py, machine_learning_hep/data/data_Dspp/database_ml_parameters_Dspp.yml, machine_learning_hep/data/data_Dspp/database_ml_parameters_Dspp_HMSPD.yml, machine_learning_hep/data/data_Dspp/database_ml_parameters_Dspp_HMV0M.yml, machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_0304.yml, machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml, machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304_HM_V0.yml, machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml, machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417_HM_V0.yml, machine_learning_hep/fitting/helpers.py, machine_learning_hep/processer.py, machine_learning_hep/processerdhadrons_mult.py
* Save histograms and canvas in root file in ML cut variation, so layout can be changed offline
* Fix for initialisation of widths for HMSPD case. The trigger weights were applied to 0-999, which makes the fit fail
* Databases for MB, HMSPD and HMV0M Ds analyses for paper proposal
* Add possibility to do INEL>0 selection
* Bug fix for efficiency when `is_ev_rej == 0` was not yet applied when unpacking (was not required for generated df)
* Calculate and store `n_tracklets_sub` as well (before only `n_tracklets_corr_sub`)
=> Ds vs mult analysis: Small fixes and extra features

cplusutilities/Download.sh, cplusutilities/README.md, cplusutilities/downloader.sh
`Download-generic.sh` should be used, but fixed some mistakes in case someone still uses `Download.sh`
=> Fix old GRID Downloader + README
